export const HANDLE_STATE_TRANSACTION_LIST = 'HANDLE_STATE_TRANSACTION_LIST';
export const FETCH_TRANSACTION_LIST = 'FETCH_TRANSACTION_LIST';
export const FETCH_TRANSACTION_LIST_SUCCESS = 'FETCH_TRANSACTION_LIST_SUCCESS';
export const FETCH_TRANSACTION_LIST_FAILURE = 'FETCH_TRANSACTION_LIST_FAILURE';
export const FILTER_BY_VALUE = 'FILTER_BY_VALUE';
export const SORT_BY_ALPHABET = 'SORT_BY_ALPHABET';
